# combining service and deployment yaml files into one single file
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users-api
        image: ngyewkong/k8s-dep-users:latest
        env:
        # using mongodb atlas to setup mongodb
        - name: MONGODB_CONNECTION_URI
          value: 'mongodb+srv://admin:VCv9g8wlkjqu7JTf@cluster0.fgwtbfz.mongodb.net/?retryWrites=true&w=majority'
        # using auth service name to ref the coredns of auth-service
        - name: AUTH_API_ADD
          value: 'auth-service.default:3000'
