apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
    # ClusterIP will not allow outside world comm (only inside the cluster)
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
