# create yaml file for users container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: ngyewkong/k8s-network-users
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
