apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
  # users-app.js container is exposing 8080 port (targetPort)
  # expose to ext on port 80
  - protocol: TCP
    port: 80
    targetPort: 8080
