# minikube service story-service -> important to specify the service name
apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: ngyewkong/k8s-data-demo
          imagePullPolicy: Always
          volumeMounts:
            # container internal path as determined by the app
            - mountPath: /app/story
              name: story-volume
        # by default volume is pod specific when pod crashes -> volumes get deleted as well
        # survives container restarts
      volumes:
        - name: story-volume
        # using emptyDir type which create a new dir which survives container restarts
          emptyDir: {}
