# docker-compose up to bring up the container using docker-compose
version: "3"
services:
  stories:
    build: .
    # add a named volume
    volumes:
      - stories:/app/story
    ports:
      - 80:3000
volumes:
  stories:
