apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  # follow the pv limit or less
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  # need to specify in pvc.yaml also
  storageClassName: standard
